import esbuild from 'esbuild';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const prod = process.argv[2] === 'production';

// Primary build output is the repo root — that's what release.yml uploads to
// the GitHub Release, what BRAT pulls down, and what the community plugin
// market expects. (Earlier versions hardcoded an absolute vault path which
// silently worked on the author's laptop but produced empty releases in CI.)
const REPO_OUTDIR = '.';

// Optional dev convenience: when GLOSSA_PLUGIN_DIR (or legacy
// NOTE_CODEX_PLUGIN_DIR) is set, ALSO mirror the build into that vault
// folder after each rebuild so the host app picks it up immediately on
// reload. Unset in CI = no mirror.
const MIRROR_DIR = process.env.GLOSSA_PLUGIN_DIR || process.env.NOTE_CODEX_PLUGIN_DIR || null;

if (MIRROR_DIR) fs.mkdirSync(MIRROR_DIR, { recursive: true });

/** Copy manifest + styles next to main.js so the artifact set is self-contained.
 *  Runs at the repo root AND, when configured, also mirrors into the vault. */
function copyStatic() {
  // (manifest.json + styles.css live at repo root already; nothing to copy
  // for the primary output. Just mirror to MIRROR_DIR when set.)
  if (!MIRROR_DIR) return;
  for (const f of ['manifest.json', 'styles.css']) {
    if (fs.existsSync(f)) fs.copyFileSync(f, path.join(MIRROR_DIR, f));
  }
  // Drop a .gitignore in the vault plugin dir so users who happen to git-track
  // their vault won't accidentally commit secrets / chats / index.
  const gi = ['# Auto-generated by build — keep secrets / chats / index out of git', '',
    'data.json',
    'chats.json',
    'checkpoints.json',
    'embeddings.json',
    '*.log',
    ''].join('\n');
  fs.writeFileSync(path.join(MIRROR_DIR, '.gitignore'), gi);
  // Also mirror main.js (esbuild only writes the primary outfile).
  if (fs.existsSync('main.js')) fs.copyFileSync('main.js', path.join(MIRROR_DIR, 'main.js'));
}

const opts = {
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian', 'electron',
    '@codemirror/autocomplete', '@codemirror/collab', '@codemirror/commands',
    '@codemirror/language', '@codemirror/lint', '@codemirror/search',
    '@codemirror/state', '@codemirror/view',
    '@lezer/common', '@lezer/highlight', '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.join(REPO_OUTDIR, 'main.js'),
  platform: 'node',
  plugins: [
    {
      name: 'static-copy',
      setup(build) {
        build.onEnd(() => {
          copyStatic();
          if (MIRROR_DIR) console.log('✓ built → repo root + mirrored to', MIRROR_DIR);
          else console.log('✓ built → repo root (no GLOSSA_PLUGIN_DIR set; skipping vault mirror)');
        });
      },
    },
  ],
};

if (prod) {
  await esbuild.build(opts);
} else {
  const ctx = await esbuild.context(opts);
  await ctx.watch();
  console.log('watching… (Ctrl+C to stop)');
}
