import esbuild from 'esbuild';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const prod = process.argv[2] === 'production';

// Build output goes directly to the vault's plugin folder so reloading is instant.
// The env-var name (GLOSSA_PLUGIN_DIR) is the user-facing override; the legacy
// NOTE_CODEX_PLUGIN_DIR is still honoured so prior CI / scripts keep working.
const VAULT_PLUGIN_DIR = process.env.GLOSSA_PLUGIN_DIR
  || process.env.NOTE_CODEX_PLUGIN_DIR
  || '/Users/wangyi/Library/Mobile Documents/iCloud~md~obsidian/Documents/yiiwang/.obsidian/plugins/glossa';

fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });

// Copy static files (manifest, styles) on each build. Also drops a .gitignore
// so users who happen to git-track their vault won't accidentally commit secrets.
function copyStatic() {
  for (const f of ['manifest.json', 'styles.css']) {
    if (fs.existsSync(f)) {
      fs.copyFileSync(f, path.join(VAULT_PLUGIN_DIR, f));
    }
  }
  // Generate .gitignore in plugin dir
  const gi = ['# Auto-generated by build — keep secrets / chats / index out of git', '',
    'data.json',
    'chats.json',
    'checkpoints.json',
    'embeddings.json',
    '*.log',
    ''].join('\n');
  fs.writeFileSync(path.join(VAULT_PLUGIN_DIR, '.gitignore'), gi);
}

const opts = {
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian', 'electron',
    '@codemirror/autocomplete', '@codemirror/collab', '@codemirror/commands',
    '@codemirror/language', '@codemirror/lint', '@codemirror/search',
    '@codemirror/state', '@codemirror/view',
    '@lezer/common', '@lezer/highlight', '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.join(VAULT_PLUGIN_DIR, 'main.js'),
  platform: 'node',
  plugins: [
    {
      name: 'static-copy',
      setup(build) {
        build.onEnd(() => {
          copyStatic();
          console.log('✓ built →', VAULT_PLUGIN_DIR);
        });
      },
    },
  ],
};

if (prod) {
  await esbuild.build(opts);
} else {
  const ctx = await esbuild.context(opts);
  await ctx.watch();
  console.log('watching… (Ctrl+C to stop)');
}
