const path = require('path');
exports.run = async (t, load) => {
  const runtime = await load(path.resolve(__dirname, '../src/agent/session_runtime.ts'));
  const session = { id: 's', messages: [], title: 'private title', createdAt: 0, updatedAt: 0, mode: 'chat', endpointId: null };
  runtime.enqueueMessage(session, 'correction', 'steer');
  runtime.enqueueMessage(session, 'next task', 'followup');
  t.eq(runtime.takeSteering(session).map(m => m.text), ['correction'], 'only steering consumed at boundary');
  t.eq(session.inbox.map(m => m.text), ['next task'], 'follow-up retained');
  for (let i = 0; i < 30; i++) runtime.enqueueMessage(session, 'more', 'steer');
  t.eq(session.inbox.length, 20, 'queue has bounded size');
  t.eq(runtime.enqueueMessage(session, ' ', 'steer'), null, 'empty input rejected');
  session.goal = runtime.newGoal('Write a summary', 900);
  t.eq(session.goal.maxRounds, 20, 'goal rounds are capped');
  session.goal.phase = 'active';
  t.ok(runtime.canContinueGoal(session.goal, true), 'armed goal can continue');
  t.ok(!runtime.canContinueGoal(session.goal, false), 'reloaded goal cannot auto-run');
  runtime.disarmGoal(session);
  t.eq(session.goal.phase, 'paused', 'stop persists paused state');
  session.goal.phase = 'active'; session.goal.rounds = 20;
  t.ok(!runtime.canContinueGoal(session.goal, true), 'round limit stops continuation');
  let saves = 0;
  const tool = runtime.goalStatusTool(session.goal, async () => saves++);
  t.eq((await tool.run({}, { phase: 'blocked', progress: 'Read source' })).status, 'error', 'blocker must be explained');
  await tool.run({}, { phase: 'blocked', progress: 'Read source', blocker: 'Need a file' });
  t.eq(session.goal.phase, 'blocked', 'status tool persists blocked state');
  t.eq(saves, 1, 'status saved once');
  t.eq((await tool.run({}, { phase: 'active', progress: 'restart' })).errorCode, 'TASK_PAUSED', 'model cannot unpause task');
  runtime.recordDiagnostic(session, { at: 2, kind: 'tool', tool: 'read_note', status: 'success', code: 'x/private-secret', args: { apiKey: 'secret-key' }, result: 'note body', path: '/private/path', durationMs: 25 });
  const report = runtime.exportDiagnostics(session, '0.8.0');
  for (const secret of ['private title', 'secret-key', 'note body', '/private/path', 'private-secret', 'Write a summary']) t.ok(!report.includes(secret), 'diagnostics exclude ' + secret);
  t.ok(report.includes('read_note') && report.includes('25'), 'diagnostics keep useful tool metadata');
  for (let i = 0; i < 600; i++) runtime.recordDiagnostic(session, { at: i, kind: 'step' });
  t.eq(session.diagnostics.length, 500, 'trace bounded');

  const { ChatStore } = await load(path.resolve(__dirname, '../src/chat_store.ts'));
  const files = new Map();
  const adapter = { exists: async p => files.has(p), read: async p => files.get(p), write: async (p, s) => files.set(p,s), mkdir: async()=>{}, list: async()=>({files:[],folders:[]}), rename: async(a,b)=>{files.set(b,files.get(a)); files.delete(a);}, remove: async p=>files.delete(p) };
  const host = { app: { vault: { adapter } }, manifest: { dir: '.obsidian/plugins/glossa' } };
  const store = new ChatStore(host);
  await store.load();
  const folder = await store.createFolder('  Research  ');
  await store.saveSession({ ...session, goal: runtime.newGoal('Retained task', 3), inbox: [], messages: [] });
  await store.moveSession('s', folder.id);
  const reopened = new ChatStore(host); await reopened.load();
  t.eq(reopened.listFolders()[0].name, 'Research', 'folders survive reload');
  t.eq(reopened.getSession('s').folderId, folder.id, 'chat membership survives reload');
  t.eq(reopened.getSession('s').goal.phase, 'paused', 'goal-only session survives reload paused');
  await reopened.renameFolder(folder.id, 'Writing');
  t.eq(reopened.listFolders()[0].name, 'Writing', 'rename updates folder');
  await reopened.deleteFolder(folder.id);
  t.ok(reopened.getSession('s') && !reopened.getSession('s').folderId, 'folder deletion keeps chats unfiled');
  const empty = await reopened.createFolder('Empty');
  const emptyReload = new ChatStore(host); await emptyReload.load();
  t.ok(emptyReload.listFolders().some(f => f.id === empty.id), 'empty folder persists');
  await emptyReload.deleteSession('s');
  const last = new ChatStore(host); await last.load();
  t.eq(last.getSession('s'), undefined, 'deleted chat does not resurrect');
};
